name: Publish latest to docker

on:
  push:
    branches:
      - master

jobs:

  release:
    if: github.repository == 'WatermelonOj/WatermelonFrontend'
    name: Build with node ${{ matrix.node_version }} on ${{ matrix.os }} and upload
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node_version: [12.x]
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v1
      - name: use Node.js ${{ matrix.node_version }}
        uses: actions/setup-node@v1
        with:
          node_version: ${{ matrix.node_version }}

      - name: publish docker
        uses: Acerkoo/Publish-Docker-Github-Action@2.7.1
        with:
          name: registry.cn-hangzhou.aliyuncs.com/watermelonoj/frontend:latest
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          registry: registry.cn-hangzhou.aliyuncs.com
          dockerfile: Dockerfile
